### ISSUE TITLE
Centreon' object has no attribute host_list'

### ISSUE THREAD

**Issue by natman** [guillaumewatteeux/ansible-centreon#9]
Hello
I can add/delete a host, but when changing status to disabled, I first get issue  "Centreon' object has no attribute host_list". 
So into centreon_host.py, I change the syntax to host.list(), but this time the issue is "'unicode' object has no attribute 'name'"
Thank you for your help.

**Comment by guillaumewatteeux** [comment]
Hi,

Witch branch ? 

I works on dev branch with new centreonapi version. Could you try with this environment ?

**Comment by natman** [comment]
So... I gave a try to many combinations but no one works, I may misunderstood.
I'm pretty sure you're talking about the dev branch ansible-centreon, but what about the centreonapi repo? Should I use your own forked repo, or the official centreon one? And with which branch?

Our centreon production is not a https one, so the only way I found to make your centreon_host  module (present/absent state only ) work is to use the eaa757898e32450510b8460ccd481be3c61c186c branch of your forked centreonapi with the master branch of ansible-centreon.

**Comment by guillaumewatteeux** [comment]
Hi,

I'm works on both projects. Fork from centreonapi is temporary. I'll merge my stuff after beta test period. (join slack #centreon-iac)
For Ansible modules (and roles). I'm works on dev branch before release a stable version.

Ansible modules on master branch not work with current centreonapi package (>0.1.3)

**Comment by natman** [comment]
okay,
so, for a 3.4 centreon, the good combination for make all modules work with an http connection is:

- master branch from ansible-centreon (awful issues with dev branch)
- detached from origin/features/ansible-centreon from your forked centreonapi 

All work as expected, and it is a very useful stuff for all-in-one playbook automation, from vm creation to monitoring.

none of other branches combinations work. 

I'll next install a 18.10 vm to give a try.
